sudo: required
dist: trusty
language: c
compiler: gcc
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra
    - latex-beamer
    - pgf
    - python-pygments
    - ghostscript
script:
  - make
notifications:
  email:
    recipients:
      - pejman@ghorbanzade.com
    on_success: always
    on_failure: always
