language: c
compiler: gcc
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra
    - latex-beamer
    - ghostscript
script:
  - make docs
notifications:
  email:
    recipients:
      - mail@ghorbanzade.com
    on_success: always
    on_failure: always
